# Plugin metrics is very helpful for plugin owner
plugin-metrics: true

# /newyear start <time in seconds> max time limit
# if you are admin you are unlimited
newyear-start-max-time-limit: 10

# The name of firework gun
firework-rocket-name: "&cFirework rocket"
# Firework gun lore
firework-rocket-lore:
  - "&eRight-click &7to fire a firework!"
  
# Set cooltime for gun to next shot(second)
cooltime: 5
# cooltime lore
cooltime-lore: "&6&lOwnNewYearEve &8» &cYou need to wait for %time% second, then you can shot!"