name: OwnNewYearEve
main: me.symi.newyear.OwnNewYearEve
author: Symi
version: 1.2
api-version: 1.16
website: https://github.com/Symii
description: With this plugin you can create awesome new year eve fireworks event

commands:
  setfirework:
    description: Set firework spawn position
    aliases: [sf]
  newyear:
    description: OwnNewYearEve plugin main command
    aliases: [onye,ownnewyeareve]

permissions:
  ownnewyeareve.admin:
    default: op
    description: Allows all commands
  ownnewyeareve.start:
    default: op
    description: Allows /newyear start <time in seconds> command
  ownnewyeareve.getgun:
    default: op
    description: Allows /newyear getgun command
  ownnewyeareve.setfirework:
    default: op
    description: Allows /setfirework command
  ownnewyeareve.reload:
    default: op
    description: Allows /newyear reload command
